version: '3.1'

services:
    backend:
        image: 809899697118.dkr.ecr.eu-west-1.amazonaws.com/ccbda/backend:local-test
        container_name: backend
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - .envs/.django.env
        environment:
            - DJANGO_SETTINGS_MODULE=djangoProject3.settings

    pg:
        image: postgres:14-alpine
        container_name: postgres-backend
        #volumes:
        #    - ./pgdata:/var/lib/postgresql/data
        env_file:
            - .envs/.postgres.env

